# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKoAMUn-FThKfVMRZbU_8BMROVvw9Ddl
"""
# -*- coding: utf-8 -*-

import streamlit as st
import unicodedata
import re
import time
import random

# ==============================
# FUNÇÕES AUXILIARES
# ==============================
def limpar_texto(texto):
    """Normaliza strings para o padrão corporativo (sem acentos, uppercase)."""
    if not texto:
        return ""
    texto = unicodedata.normalize("NFKD", texto)
    texto = texto.encode("ASCII", "ignore").decode("ASCII")
    texto = texto.replace("°", "")
    texto = re.sub(r"[^\w\s-]", "", texto)
    texto = re.sub(r"\s+", " ", texto)
    return texto.strip().upper()

def bot_message(texto, delay=2.0):
    """Simula interação do bot com spinner fixo de 2 segundos."""
    pensamentos = [
        "🤔 Analisando os parâmetros...", 
        "🔎 Consultando o padrão corporativo...", 
        "✍️ Preparando a nomenclatura...", 
        "📄 Organizando metadados..."
    ]
    with st.chat_message("assistant"):
        with st.spinner(random.choice(pensamentos)):
            time.sleep(delay)
        st.markdown(texto)

# ==============================
# CONFIGURAÇÃO DA PÁGINA
# ==============================
st.set_page_config(
    page_title="EEB Name Generator",
    page_icon="📄",
    layout="centered"
)

# ==============================
# ESTILO CSS
# ==============================
st.markdown("""
<style>
    /* Estilo do Avatar do Assistente (Azul) */
    [data-testid="stChatMessageAvatarAssistant"] { 
        background-color: #007bff !important; 
    }
    
    /* Estilo do Avatar do Usuário (Cinza Escuro) */
    [data-testid="stChatMessageAvatarUser"] { 
        background-color: #333333 !important; 
    }

    /* Botão Padrão */
    div.stButton > button {
        background-color: #333333;
        color: white;
        border-radius: 8px;
    }

    /* BOTÃO LISTA: VERMELHO E ALINHADO À DIREITA */
    div[data-testid="stVerticalBlock"] > div:has(button[key="lista_fixa"]) {
        display: flex !important;
        justify-content: flex-end !important;
    }

    button[key="lista_fixa"] {
        background-color: #dc3545 !important;
        color: white !important;
        border: none !important;
        padding: 0.5rem 1.2rem !important;
        font-weight: bold !important;
    }

    button[key="lista_fixa"]:hover {
        background-color: #a71d2a !important;
    }

    /* Botão Primário (Verde) */
    div.stButton > button[kind="primary"] {
        background-color: #28a745 !important;
        border: none !important;
    }
</style>
""", unsafe_allow_html=True)

# ==============================
# HEADER (LOGO CENTRALIZADA)
# ==============================
col1, col2, col3 = st.columns([1, 0.4, 1]) 
with col2:
    try:
        st.image("EBB LOGO PRETO.png", use_container_width=True) 
    except:
        pass

st.markdown("<h1 style='text-align:center;'>EEB GENERATOR NAME</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align:center;color:gray;'>Padronização de documentos corporativos</p>", unsafe_allow_html=True)
st.markdown("---")

# ==============================
# DICIONÁRIOS DE DADOS
# ==============================
TIPOS = {"Aditivos": "ADT", "Cartas": "CRT", "Cessão de direitos": "CDDA", "Distratos": "DIS", "Contratos de edição e termos": "CE", "Termos": "TRM"}
SEGMENTOS = {"Ensino Infantil": "EI", "Ensino Fundamental Anos Iniciais": "EFAI", "Ensino Fundamental Anos Finais": "EFAF", "Ensino Médio": "EM", "Ensino Médio Pré Vestibular": "EM PV"}
SELOS = ["Ática","Scipione","Saraiva","Anglo","PH","SOMOS","Amplia","Ético","Fibonacci","PLURALL","Rede Cristã","Videoaulas","Pitágoras","Mind Makers","Maxi","Farias Brito","Eduall"]
ANOS = ["1° Ano","2° Ano","3° Ano","4° Ano","5° Ano","6° Ano","7° Ano","8° Ano","9° Ano","1° Série","2° Série","4° Série"]

if "step" not in st.session_state:
    st.session_state.step = 1
    st.session_state.data = {}

# ==============================
# VIEW: LISTA DE ABREVIAÇÕES (STEP 99)
# ==============================
if st.session_state.step == 99:
    st.subheader("📋 Referência de Abreviações")
    c1, c2 = st.columns(2)
    with c1:
        st.write("**Contratos**")
        for k, v in TIPOS.items(): st.code(f"{v} : {k}")
    with c2:
        st.write("**Segmentos**")
        for k, v in SEGMENTOS.items(): st.code(f"{v} : {k}")
    
    if st.button("⬅️ Voltar"):
        st.session_state.step = 1
        st.rerun()

# ==============================
# VIEW: FLUXO PRINCIPAL
# ==============================
else:
    if st.session_state.step == 1:
        with st.chat_message("assistant"): 
            st.write("Olá! 👋 Sou seu assistente de padronização. Vamos batizar esse documento?")
        
        with st.chat_message("user"):
            tipo = st.selectbox("Selecione o Tipo de Contrato:", list(TIPOS.keys()))
        if st.button("Confirmar", type="primary"):
            st.session_state.data["tipo"] = TIPOS[tipo]
            st.session_state.step = 2
            st.rerun()

    elif st.session_state.step == 2:
        bot_message("Ótimo. Agora, selecione o **selo** correspondente.")
        with st.chat_message("user"):
            selo = st.selectbox("Selo:", SELOS)
        if st.button("Confirmar", type="primary"):
            st.session_state.data["selo"] = limpar_texto(selo)
            st.session_state.step = 3
            st.rerun()

    elif st.session_state.step == 3:
        bot_message("Entendido. Qual o **ano ou série**?")
        with st.chat_message("user"):
            ano = st.selectbox("Ano/Série:", ANOS)
        if st.button("Confirmar", type="primary"):
            st.session_state.data["ano"] = limpar_texto(ano)
            st.session_state.step = 4
            st.rerun()

    elif st.session_state.step == 4:
        bot_message("Perfeito. Qual o **segmento** de ensino?")
        with st.chat_message("user"):
            seg = st.selectbox("Segmento:", list(SEGMENTOS.keys()))
        if st.button("Confirmar", type="primary"):
            st.session_state.data["segmento"] = SEGMENTOS[seg]
            st.session_state.step = 5
            st.rerun()

    elif st.session_state.step == 5:
        bot_message("Estamos quase lá. Quem é o **autor**?")
        with st.chat_message("user"):
            autor = st.text_input("Nome do Autor:")
        if st.button("Confirmar", type="primary"):
            if autor.strip():
                st.session_state.data["autor"] = limpar_texto(autor)
                st.session_state.step = 6
                st.rerun()
            else:
                st.error("Por favor, insira o nome do autor para continuar.")

    elif st.session_state.step == 6:
        bot_message("Agora, me diga o nome da **obra**.")
        with st.chat_message("user"):
            obra = st.text_input("Título da Obra:")
        if st.button("Confirmar", type="primary"):
            if obra.strip():
                st.session_state.data["obra"] = limpar_texto(obra)
                st.session_state.step = 7
                st.rerun()
            else:
                st.error("O título da obra é obrigatório.")

    elif st.session_state.step == 7:
        bot_message("Este documento é referente a uma **solicitação de terceiros**?")
        col1, col2 = st.columns(2)
        if col1.button("Sim", type="primary", use_container_width=True):
            st.session_state.data["terceiros"] = True
            st.session_state.step = 70
            st.rerun()
        if col2.button("Não", use_container_width=True):
            st.session_state.data["terceiros"] = False
            st.session_state.step = 8
            st.rerun()

    elif st.session_state.step == 70:
        bot_message("Pode informar o **ID da solicitação**, por favor?")
        with st.chat_message("user"):
            id_sol = st.text_input("ID:")
        if st.button("Finalizar", type="primary"):
            if id_sol.strip():
                st.session_state.data["id_terceiros"] = limpar_texto(id_sol)
                st.session_state.step = 8
                st.rerun()
            else:
                st.error("Insira o ID para finalizar.")

    elif st.session_state.step == 8:
        bot_message("Tudo pronto! Aqui está a nomenclatura padronizada:")
        d = st.session_state.data
        res = [d['tipo'], d['selo'], d['autor'], d['obra'], d['ano'], d['segmento']]
        if d.get("terceiros"): res.append(d['id_terceiros'])
        
        # O resultado final aparece SEM o chat_message("user")
        st.code(" - ".join(res), language="text")
        
        if st.button("🔄 Gerar outro nome"):
            st.session_state.clear()
            st.rerun()

    st.write("---")
    if st.button("📋 Lista de Abreviações", key="lista_fixa"):
        st.session_state.step = 99
        st.rerun()
